### ISSUE TITLE
Add source reference in comments

### ISSUE THREAD

**Issue by 0xbok** [plume-sig/zk-nullifier-sig#16]
https://github.com/miracl/core/blob/master/javascript/examples/node/TestHTP.js#L37 for https://github.com/zk-nullifier-sig/zk-nullifier-sig/blob/main/javascript/src/utils/hashToCurve.ts#L33

`hashToPairing()` function is taken from `htp()` function in `TestHTP.js`. Best to add this information in comments. Just makes the life of the reader easier. You can add commit info to the source link.

**Comment by RajeshRk18** [comment]
#45
