### ISSUE TITLE
Remove `sha512` and dependencies

### ISSUE THREAD

**Issue by 0xbok** [plume-sig/zk-nullifier-sig#20]
https://github.com/plume-sig/zk-nullifier-sig/blob/main/javascript/src/signals.ts#L10

it's not used.

**Comment by Divide-By-0** [comment]
Also needs to be fixed in rust: https://github.com/plume-sig/zk-nullifier-sig/blob/1ce160710b398b75271dc9b75d3f766a6160c920/rust-arkworks/src/lib.rs#L99

**Comment by skaunov** [comment]
Is here anything to do? Looks to me like it should be just closed.
