### ISSUE TITLE
Consistent naming across different implementations

### ISSUE THREAD

**Issue by 0xbok** [plume-sig/zk-nullifier-sig#22]
Same values are named differently across implementations. While it's not a big deal for small code size, it helps the reader if they can be named same throughout. 

For example: `h[m,pk]^r` is called:
- [`z` in arkworks impl](https://github.com/plume-sig/zk-nullifier-sig/blob/main/rust-arkworks/src/lib.rs#L211),
- [`hash_m_pk_pow_r` in k-256 impl](https://github.com/plume-sig/zk-nullifier-sig/blob/main/rust-k256/src/lib.rs#L97),
- [`hashMPkPowR` in js](https://github.com/plume-sig/zk-nullifier-sig/blob/main/javascript/src/signals.ts#L52) and
- [`h_pow_r` in circom](https://github.com/plume-sig/zk-nullifier-sig/blob/main/circuits/verify_nullifier.circom#LL109C19-L109C26)

Differing upto casing is fine, but arkworks impl variable name deviates the most from others.

**Comment by skaunov** [comment]
I'll groom things, though particular examples which absolutely require attention would be beneficial.

**Comment by skaunov** [comment]
I guess it's best to choose naming based on _the blog post,_ paper, and then some best judgement / linting?

**Comment by Divide-By-0** [comment]
> I guess it's best to choose naming based on _the blog post,_ paper, and then some best judgement / linting?

That seems great. Also we can make edits to the blog post to include that terminology :p

https://github.com/Divide-By-0/blog/blob/main/content/posts/nullifier.md

**Comment by skaunov** [comment]
> > I guess it's best to choose naming based on _the blog post,_ paper, and then some best judgement / linting?
> 
> That seems great. Also we can make edits to the blog post to include that terminology :p
> 
> https://github.com/Divide-By-0/blog/blob/main/content/posts/nullifier.md

I can share my own experience: when first exposed to the scheme/protocol this `hash` & `hash2` thing isn't make it really easier to follow. Do you think they could be more semantic?

**Comment by Divide-By-0** [comment]
> > That seems great. Also we can make edits to the blog post to include that terminology :p
> > https://github.com/Divide-By-0/blog/blob/main/content/posts/nullifier.md
> 
> I can share my own experience: when first exposed to the scheme/protocol this `hash` & `hash2` thing isn't make it really easier to follow. Do you think they could be more semantic?

perfect! you should be able to fork slides.plume.run and the md blog post to be consistent with the semantic changes you made here, if you think it would help. im also now wondering if docs would be helpful!
