### ISSUE TITLE
`c` modulus is inconsistent across different implementations

### ISSUE THREAD

**Issue by 0xbok** [plume-sig/zk-nullifier-sig#23]
If `c` overflows the Curve order, the value returned by Rust impls differ from js and circom versions.

Rust impls return `c % Curve.n`, js and circom return the plain `c`.

**Comment by skaunov** [comment]
Feels obvious, but let me double check: _we want it returned wrapped_, right? Like currently in Rust done.

**Comment by Divide-By-0** [comment]
Wrapped seems good!

**Comment by skaunov** [comment]
I've fixed this for <./rust_k256> in a local branch, and need input on #39 to finish.
