### ISSUE TITLE
SHA-512 in `rust-arkworks`

### ISSUE THREAD

**Issue by skaunov** [plume-sig/zk-nullifier-sig#39]
I noticed that both `c` are produced with SHA-256 in <./javascript>. Is it ok to that crate to do it with SHA-512?

**Comment by Divide-By-0** [comment]
Oh we are removing sha512 everywhere and only using sha256.

**Comment by skaunov** [comment]
What would be corrected test vectors for <https://github.com/plume-sig/zk-nullifier-sig/blob/e7490a8c42d70988d3903a15c448ab1dfa62a807/rust-arkworks/src/tests.rs#L215> in that case?

**Comment by Divide-By-0** [comment]
Feel free to just calculate that for i.e. the test anvil sk/pk in the implementation and use that as a test; if the other implementations all give the same result, we can be pretty confident that its calculating correctly!
