### ISSUE TITLE
Upgrade `ark-ec` in <rust-arkworks> to "~0.4.0"

### ISSUE THREAD

**Issue by skaunov** [plume-sig/zk-nullifier-sig#43]
There's substantial [number of different improvements](https://github.com/arkworks-rs/algebra/blob/master/CHANGELOG.md#breaking-changes-3) since "0.3.0" which is used now. I guess it'd not only generally improve execution, but also might enable simplification of some current helpers introduced in the code.

**Comment by Divide-By-0** [comment]
Go for it!

**Comment by skaunov** [comment]
Likely will require upgrade of `secp256k1 = { git = "https://github.com/geometryresearch/ark-secp256k1.git" }` too. On the other hand chances are `~0.4.0` provide stuff that is provided by that crate now.
