### ISSUE TITLE
Crates API and documentation

### ISSUE THREAD

**Issue by skaunov** [plume-sig/zk-nullifier-sig#67]
Both crates basically lacks documentation, and <./rust-k256> lacks API choices.

Also their `name` are ...temporary.

PS It would be nice to think about traits used and reexported so that it would not clash with versions that downstream use. Though most likely Cargo will do its job on it, just it's better to be sure. 
This one is more about releasing the crates when things will come to it.

**Comment by skaunov** [comment]
We should consider to release the crate with the traits which would define API and then use it in own implementations and enable foreign.

I'm not sure yet about downsides of this approach aside from some added complexity which would buy uniformity of all implementations. So counter arguments are welcome.

**Comment by Divide-By-0** [comment]
I don't expect most people to use the crate anyways since it'll require custom logic to get the secret key in there and don't know any rust wallets.

Agree on adding docs and making name more uniform.

**Comment by skaunov** [comment]
From the top of my head I would name Solana. X) Didn't check Polkadot, 
but would place a bet on it too.

**Comment by Divide-By-0** [comment]
Got it -- that makes sense, I don't know anything about those. Traits seem fine to me -- the complexity shouldn't be that high on our side right, just implementing the trait twice? As long as almost everything is pub, I'm OK with that.

**Comment by Divide-By-0** [comment]
Can you make a gitbook or mdbook and make this? there should automatically be cargo docs from the docstrings right

**Comment by skaunov** [comment]
> Can you make a gitbook or mdbook and make this? Also, can you publish a cargo crate -- there should automatically be cargo docs from the docstrings right?

Yep. Here it's needed to groom the interfaces and write those docstring.

**Comment by skaunov** [comment]
> We should consider to release the crate with the traits which would define API and then use it in own implementations and enable foreign.
> 
> I'm not sure yet about downsides of this approach aside from some added complexity which would buy uniformity of all implementations. So counter arguments are welcome.

I remember thinking about this as now experimented a bit with some traits like this.
```rust
pub trait Plume<CG: CurveGroup> {
    type SignaturePrivate: Zeroize;
    type SignaturePublic;
    fn sign_with_r(
        is_v1: bool, sk: CG::Config::ScalarField, message: &[u8], r: CG::Config::ScalarField
    ) -> (SignaturePrivate, SignaturePublic);
    fn sign(
        is_v1: bool, sk: CG::Config::ScalarField, message: &[u8]
    ) -> (SignaturePrivate, SignaturePublic);
}
```

So counter arguments are the following. Very few advantages: less boiler-plate, uniformity of approach. Even a default implementation for `sign` looks sad here since it would restrict a scalar unnecessarily, hence `sign` should be in a trait which uses this trait. `ZeroizeOnDrop` is another thing to add, but it's not suitable for the `wasm-bindgen` so another piece to have a higher-order trait. Then when step outside of `arkworks` that will bring own traits which will be implemented by the traits of the system which is used for the implementation. And finally there's no wide audience to enjoy all of this uniformity and ubiquitous approach. So at the current state of affairs re-implementations are better and more clear.
