### ISSUE TITLE
`tests` in <./rust-k256> are confusing

### ISSUE THREAD

**Issue by skaunov** [plume-sig/zk-nullifier-sig#69]
Tests in _rust_k256_ use the same function while producing test data as the function they test. So actually they test wrapping (which is useful too), but `c_sha256_vec_signal` is left untested in fact.

**Comment by skaunov** [comment]
Delving into shows that I'm actually wrong, and it's tested, but not well attributed, see <https://github.com/plume-sig/zk-nullifier-sig/blob/79c602670b8448c9a85d552ba8a8d8aa5bbede04/rust-k256/src/lib.rs#L417>.

Not closing this issue to decide if we need refactor `tests` to make it more comprehensible.

**Comment by skaunov** [comment]
I published current solution in <branch:69>, thought to finalize it I need the answer to #84 . @Divide-By-0

**Comment by Divide-By-0** [comment]
> I published current solution in branch:69, thought to finalize it I need the answer to #84 . @Divide-By-0

Yup, we should make the signing function pub too.

**Comment by skaunov** [comment]
> > I published current solution in branch:69, thought to finalize it I need the answer to #84 . @Divide-By-0
> 
> Yup, we should make the signing function pub too.

Cool! Though there's no signing function yet. X)
