### ISSUE TITLE
Add `sign` method to <./rust-k256>

### ISSUE THREAD

**Issue by skaunov** [plume-sig/zk-nullifier-sig#84]
Seems like <./rust-k256> designed only for verification of a signature, as there's no ready outlet to `pub` which could _sign_ a message. Should it be so, or does it just lacking it?

**Comment by skaunov** [comment]
Depending on the answer I would raise an issue for changing the `struct` parts to `AsRef` or creating some facility methods for instantiation of the signature.

**Comment by Divide-By-0** [comment]
yes we definitely need a plume signing function!

**Comment by Divide-By-0** [comment]
> [skaunov](https://github.com/skaunov)
should add that it's also needed to
* convert `tests` to integration,
* clean hex strings assertions for further comprehensibilty. \
(This well might demote `AsRef` issue to a _nice to have_ thing.)

**Comment by skaunov** [comment]
@Divide-By-0 , what do you think should we provide a sign with given $r$ method? I'm hesitant since it'd encourage nonce reuse and consequence break of the protocol. So I'm inclined to hide such a method in a debug target.

**Comment by Divide-By-0** [comment]
> @Divide-By-0 , what do you think should we provide a sign with given r method? I'm hesitant since it'd encourage nonce reuse and consequence break of the protocol. So I'm inclined to hide such a method in a debug target.

Agreed. Sounds good to me
