### ISSUE TITLE
`ProjectivePoint` should be avoided in interfaces

### ISSUE THREAD

**Issue by skaunov** [plume-sig/zk-nullifier-sig#86]
As it's known to be leaking some information. At least <rust-k256> was using it for the input on verification.

**Comment by Divide-By-0** [comment]
Can you help me understand what information it leaks?

**Comment by skaunov** [comment]
Generally implementations offer no guarantees $z$ doesn't carry information about scalar after multiplication, so we usually avoid to bring it over the boundary. Hence it really not even expected by a downstream developer.On Jan 30, 2024 8:37 PM, Yush G ***@***.***> wrote:
Can you help me understand what information it leaks?

**Comment by 0xbok** [comment]
@skaunov @Divide-By-0 i'm curious to know more about this:

> Generally implementations offer no guarantees $z$ doesn't carry information about the scalar after multiplication, so we usually avoid to bring it over the boundary. Hence it really not even expected by a downstream developer.

How does using a projective point makes it possible to carry information about the scalar?

**Comment by skaunov** [comment]
@0xbok , it's like $z$ depends on the number of the group operation the point undergone. I can find a link for you for more details.

**Comment by 0xbok** [comment]
ok, found this https://www.iacr.org/archive/eurocrypt2004/30270258/projective.pdf. will go through this at some point
