### ISSUE TITLE
`nullifier` is treated just like an EC point

### ISSUE THREAD

**Issue by skaunov** [plume-sig/zk-nullifier-sig#95]
@Divide-By-0 , how much care should `nullifier` receive compared with the secret key, and the random nonce (they receive different care, ofc)?

**Comment by Divide-By-0** [comment]
> @Divide-By-0 , how much care should `nullifier` receive compared with the secret key, and the random nonce (they receive different care, ofc)?

Nullifer will be public, doesn't need care.

**Comment by skaunov** [comment]
That's cool! Just wanted to double-check.
